name: Build and Archive Xcode Project

on:
  push:
    branches:
      - main    # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main    # Trigger workflow on PR to the main branch

jobs:
  build:
    runs-on: macos-latest  # This will run the build on a macOS runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v2
      with:
        xcode-version: '14.x'  # Set this to the version of Xcode you're using

    - name: Install Dependencies (CocoaPods, Carthage, etc.)
      run: |
        # If you're using CocoaPods, uncomment the following line
        # gem install cocoapods
        # pod install

        # If you're using Carthage, uncomment the following line
        # brew install carthage
        # carthage update --platform iOS

    - name: Build Xcode Project
      run: |
        xcodebuild clean build \
          -workspace "Review Tracker.xcworkspace" \  # Replace with your workspace name if different
          -scheme "Review Tracker" \                 # Replace with your scheme name if different
          -sdk iphoneos \
          -configuration Release

    - name: Archive Xcode Project
      run: |
        xcodebuild clean archive \
          -workspace "Review Tracker.xcworkspace" \  # Replace with your workspace name if different
          -scheme "Review Tracker" \                 # Replace with your scheme name if different
          -sdk iphoneos \
          -archivePath ${{ github.workspace }}/build/ReviewTracker.xcarchive  # Replace with your desired archive name

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath ${{ github.workspace }}/build/ReviewTracker.xcarchive \  # Replace with your archive path
          -exportPath ${{ github.workspace }}/build \
          -exportOptionsPlist ExportOptions.plist  # Create an ExportOptions.plist for distribution

    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ReviewTracker-IPA
        path: ${{ github.workspace }}/build/*.ipa  # This will upload the IPA to GitHub Actions artifacts
